@baseUrl = https://localhost:7193/api/reading-progress
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMTRjMTM0YS04YmU3LTQ4OTgtYmRiYi0wNjM5N2Q0MWQxOWYiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJkaXNwbGF5TmFtZSI6InVwZGF0ZWQgdGVzdCB1c2VyIiwiZXhwIjoxNzY5OTA4NTE4LCJpc3MiOiJVc2VyTWFuYWdlbWVudEFQSSIsImF1ZCI6IlVzZXJNYW5hZ2VtZW50Q2xpZW50In0.GUGn_2mryYhJcbXEZP9MtJZWGUWfxqILY6KCqFsgC1w

### Get test endpoint with token authorization
GET {{baseUrl}}/test
Authorization: Bearer {{token}}


### Add reading list
POST {{baseUrl}}/reading-lists
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "ManhwaId": "123"
}