@baseUrl = https://localhost:7193/api/reading-progress
@authUrl = https://localhost:7100/api/auth
@token = {{login.response.body.$.accessToken}}

### Login User
# @name login
POST {{authUrl}}/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test123!"
}


### Add reading list
POST {{baseUrl}}/reading-lists
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "ManhwaId": "123"
}

### Add reading progress event
POST {{baseUrl}}/reading-progress-events
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "ManhwaId": "456",
  "ChapterNumber": 50
}