@baseUrl = https://localhost:7100/api
@token = {{login.response.body.$.accessToken}}

### Register User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "Email": "test@example.com",
  "DisplayName": "i am a test user",
  "Password": "Test123!",
  "ConfirmPassword": "Test123!"
}

### Login User
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test123!"
}

### Get User Profile (add JWT token after login)
GET {{baseUrl}}/users/test@example.com
Authorization: Bearer {{token}}

### Update User display name (add JWT token after login)
PUT {{baseUrl}}/users/test@example.com?displayName=Updatedddd%20Test%20User
Authorization: Bearer {{token}}
